### ISSUE TITLE
bad style: assign value to meaningful variable

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#34]
Nobody can understand what that does unless they happen to know what value the 11th position after the split holds. How to do this: assign the value to a meaningful variable and return that one.

https://github.com/core-unit-bioinformatics/cubi-tools/blob/041731d1fa2c4b0d960000748185f9110410ff90/cubi-tools/update_workflow.py#L223

**Comment by svenwillger** [comment]
A meaningful variable was assigned and a description what the value is was added.
Additionally, at this point I included a check whether the API rate limit is exceeded, because if so, the error message used to be `sha1SumRef.stdout.split('"')[11] IndexError: list index out of range` which is not helpful. 
Also, since the same error message was shown if branch/tag and/or file-to-update wasn't in this branch/tag I included checks with meaningful error messages.
