### ISSUE TITLE
why is this static copy necessary?

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#38]
I still do not understand what you are trying to achieve here (with this static copy):

https://github.com/core-unit-bioinformatics/cubi-tools/blob/c734424b5f929cae7f0b601e9290f434bb90ab5b/cubi-tools/update_metadata.py#L40

Cloning the the `template-metadata` repository or using the existing clone (if it had already been cloned by the user next to the project repository) IS a copy, why are you not just using that?!

1. is there a `template-metadata` folder [repository] parallel to the project repository?
2. yes: ok, use it
3. no: ok, clone it
4. in this repository, switch to the branch/tag that you need, make sure all latest changes are available (`git pull --all`) and start the update

**Comment by svenwillger** [comment]
My thought process is that I don't now if the user has the `template-metadata` repo on his/her computer or how it's named so instead of searching or guessing I just download the `template-metadata or -workflow` and put it where I want. So in line 40 I define where I want the clone to be put. This is just to have a variable that contains the path to the cloned `template-metadata` repository that will be used.
 
For the obvious reason that you mentioned that putting the static copy inside the project repo is bad the `template.metadata/[branch/version tag]` folder  is now parallel to the project repository.

Since I only want to keep the static copy of the `template.metadata/[branch/version tag]` folder for the duration of the update and minimize the amount of data to transfer I only download the branch/version tag of interest. If the user wants to keep the files, because he/she wants to e.g. update more local repos I implemented an option to keep it parallel to the project repo and each time the script is called `git pull --all` makes sure the desired branch/version tag is up-to-date. (This only works if the other local project repos that will be updated are also parallel to the first project repo!)
If this switch is not set the whole static temp folder with all potentially downloaded branches/version tags will be deleted.

**Comment by ptrebert** [comment]
There is no searching or guessing involved and the name of the repository is fixed. That's a canonical case for "just to the simplest thing and fail if that doesn't work" (here, "the user" is certainly a CUBI member).
Just get the parent directory of the `project-dir`, check if a folder named `template-metadata-files` exists in that location and if so, just assume it's the git repo and run a git pull --all (the metadata repo is tiny, there is no point in not pulling everything). If the git command fails because the folder is actually not a git repo, just fail loud and clear.
If no such folder exists, run git clone and proceed ...

**Comment by svenwillger** [comment]
I changed the script so it does exactly what you described. 
1. Look for `template-metadata-files` folder in the parent directory of the `project-dir`
2. If present, run git pull --all and if requested checkout the desired branch/version tag
3. If not present clone the whole repo in the parent directory of the `project-dir` (the --keep option was removed, so it will stay there) and if requested checkout the desired branch/version tag
4. If folder is not a git repo or the requested branch/version tag stop script and describe clearly what the problem is
I only had to add an additional command at the end of the script to always checkout the 'main' branch at the end because there will be a git warning in subsequent runs if a version tag was used instead of a branch because we are using git pull --all and git requires an actual branch to merge to. This could be "avoided" if use git fetch --all but I don't see any advantage in that except saving some lines of code (L86-100).
