### ISSUE TITLE
improper path building and repeated code

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#44]
This line appears at least 4 times in the following 20 lines or so and exhibits 2 problems:

1) you are not using `pathlib` built-ins to construct the path despite dealing with path objects all the time. There is, e.g., the function `.with_suffix()`.

2) Instead of constructing the path and assigning it to a meaningful variable name, you just keep repeating the same pattern over and over again. I have no clue what `x` refers and single-letter variable names also violate PEP8 (exceptions for, e.g., loop variables are fine).

https://github.com/core-unit-bioinformatics/cubi-tools/blob/33c72d2ad41b229a870d67694c9088fef28e2a4a/cubi-tools/update_metadata.py#L394

**Comment by svenwillger** [comment]
That whole section was inherited and was a thorn in my side and I just kept it because it was working. It took me a long time to figure out what Sven even was doing or trying to do. E.g. this "temp" file you mention in L394 was completely unnecessary and took a lot of code to create and remove in the most inconvenient possible way and other pieces were created multiple times.
I rewrote the whole function including a helper function to make it hopefully clearer.
